// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/displayhq/CleanMinimal.tsx": () => import("../components/mockups/displayhq/CleanMinimal.tsx"),
  "./components/mockups/displayhq/EnterpriseDark.tsx": () => import("../components/mockups/displayhq/EnterpriseDark.tsx"),
  "./components/mockups/displayhq/SleekPro.tsx": () => import("../components/mockups/displayhq/SleekPro.tsx")
};
